# Site settings
name: Pangeun's Blog
email: pangeun.kim@gmail.com
author: Pangeun Kim
url: pangeun.github.io
resume_site: https://www.linkedin.com/in/pangeunkim/
github: https://github.com/pangeun/
baseurl: ""
description: 백발의 개발자를 꿈꾸고 있습니다.
meta_description: AWS, NCP, PHP7, MYSQL, NoSQL, Nodejs, React, DaynamoDB
motto: 백번의 말보다 한번의 실행으로 결과를 만들자.
banner: 시간과 노력은 배신하지 않는다.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: pangeun

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
